import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/labstaffsignupone">LabStaffSignupOne</Link>
        </li>
        <li>
          <Link to="/labstaffloginpage">LabStaffLoginPage</Link>
        </li>
        <li>
          <Link to="/labstaffsignuptwo">LabStaffSignupTwo</Link>
        </li>
        <li>
          <Link to="/labstaffsignupthree">LabStaffSignupThree</Link>
        </li>
        <li>
          <Link to="/labstaffdashboard">LabStaffDashboard</Link>
        </li>
        <li>
          <Link to="/radiologistsignupone">RadiologistSignupOne</Link>
        </li>
        <li>
          <Link to="/labstafftestpending">LabStaffTestPending</Link>
        </li>
        <li>
          <Link to="/radiologistloginpage">RadiologistLoginPage</Link>
        </li>
        <li>
          <Link to="/radiologistsignuptwo">RadiologistSignupTwo</Link>
        </li>
        <li>
          <Link to="/patientsignupone">PatientSignupOne</Link>
        </li>
        <li>
          <Link to="/radiologistsignupthree">RadiologistSignupThree</Link>
        </li>
        <li>
          <Link to="/patientguardianinfoone">PatientGuardianInfoOne</Link>
        </li>
        <li>
          <Link to="/patientloginpage">PatientLoginPage</Link>
        </li>
        <li>
          <Link to="/patientsignuptwo">PatientSignupTwo</Link>
        </li>
        <li>
          <Link to="/patientgaurdianinfotwo">PatientGaurdianInfoTwo</Link>
        </li>
        <li>
          <Link to="/radiologistdashboard">RadiologistDashboard</Link>
        </li>
        <li>
          <Link to="/patientsignupthree">PatientSignupThree</Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpatientdetails">
            RadiologistConsultationPatientDetails
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpatientdetails">
            RadiologistOwnPatientDetails
          </Link>
        </li>
        <li>
          <Link to="/patientdashboard">PatientDashboard</Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpendingforreview">
            RadiologistConsultationPendingForReview
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpendingforreviewbydoctor">
            RadiologistConsultationPendingForReviewByDoctor
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationdiagnosiscompleted">
            RadiologistConsultationDiagnosisCompleted
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpendingforreview">
            RadiologistOwnPendingForReview
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpendingforreviewbydoctor">
            RadiologistOwnPendingForReviewByDoctor
          </Link>
        </li>
        <li>
          <Link to="/radiologistowndiagnosiscompleted">
            RadiologistOwnDiagnosisCompleted
          </Link>
        </li>
        <li>
          <Link to="/patientpendingforreviewbyradiologist">
            PatientPendingForReviewByRadiologist
          </Link>
        </li>
        <li>
          <Link to="/patientpendingforreviewbydoctor">
            PatientPendingForReviewByDoctor
          </Link>
        </li>
        <li>
          <Link to="/patientdiagnosiscompleted">PatientDiagnosisCompleted</Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpfrimageannotater">
            RadiologistConsultationPFRImageAnnotater
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpfrimageannotater">
            RadiologistOwnPFRImageAnnotater
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpfrconsultotherradiologists">
            RadiologistConsultationPFRConsultOtherRadiologists
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpfrconsultotherradiologists">
            RadiologistOwnPFRConsultOtherRadiologists
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpfrbdimageannotater">
            RadiologistConsultationPFRBDImageAnnotater
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpfrbdimageannotater">
            RadiologistOwnPFRBDImageAnnotater
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpfrbdconsultotherradiologists">
            RadiologistConsultationPFRBDConsultOtherRadiologists
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpfrbdconsultotherradiologists">
            RadiologistOwnPFRBDConsultOtherRadiologists
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpendingforreviewbyradiologist">
            RadiologistConsultationPendingForReviewByRadiologist
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationpendingforreviewbydoctorhisto">
            RadiologistConsultationPendingForReviewByDoctorHisto
          </Link>
        </li>
        <li>
          <Link to="/radiologistconsultationdiagnosiscompletedhistory">
            RadiologistConsultationDiagnosisCompletedHistory
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpendingforreviewbyradiologisthistory">
            RadiologistOwnPendingForReviewByRadiologistHistory
          </Link>
        </li>
        <li>
          <Link to="/radiologistownpendingforreviewbydoctorhistory">
            RadiologistOwnPendingForReviewByDoctorHistory
          </Link>
        </li>
        <li>
          <Link to="/radiologistowndiagnosiscompletedhistory">
            RadiologistOwnDiagnosisCompletedHistory
          </Link>
        </li>
        <li>
          <Link to="/usertypeselection">Usertypeselection</Link>
        </li>
        <li>
          <Link to="/doctorsignupone">DoctorSignupOne</Link>
        </li>
        <li>
          <Link to="/adminsignupone">AdminSignupOne</Link>
        </li>
        <li>
          <Link to="/doctorloginpage">DoctorLoginPage</Link>
        </li>
        <li>
          <Link to="/doctorsignuptwo">DoctorSignupTwo</Link>
        </li>
        <li>
          <Link to="/adminloginpage">AdminLoginPage</Link>
        </li>
        <li>
          <Link to="/adminsignuptwo">AdminSignupTwo</Link>
        </li>
        <li>
          <Link to="/doctorsignupthree">DoctorSignupThree</Link>
        </li>
        <li>
          <Link to="/adminsignupthree">AdminSignupThree</Link>
        </li>
        <li>
          <Link to="/adminviewdoctors">AdminViewDoctors</Link>
        </li>
        <li>
          <Link to="/adminreviewsignuprequests">AdminReviewSignupRequests</Link>
        </li>
        <li>
          <Link to="/admindashboard">AdminDashboard</Link>
        </li>
        <li>
          <Link to="/doctordashboard">DoctorDashboard</Link>
        </li>
        <li>
          <Link to="/doctorprescribetestverification">
            DoctorPrescribeTestVerification
          </Link>
        </li>
        <li>
          <Link to="/doctorprescribetestentertestdetails">
            DoctorPrescribeTestEnterTestDetails
          </Link>
        </li>
        <li>
          <Link to="/adminviewradiologists">AdminViewRadiologists</Link>
        </li>
        <li>
          <Link to="/adminreviewaccountmodificationrequests">
            AdminReviewAccountModificationRequests
          </Link>
        </li>
        <li>
          <Link to="/adminviewlabstaff">AdminViewLabStaff</Link>
        </li>
        <li>
          <Link to="/adminreviewaccountdeletionrequests">
            AdminReviewAccountDeletionRequests
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationpatientdetails">
            DoctorConsultationPatientDetails
          </Link>
        </li>
        <li>
          <Link to="/doctorownpatientdetails">DoctorOwnPatientDetails</Link>
        </li>
        <li>
          <Link to="/doctorconsultationpendingforreview">
            DoctorConsultationPendingForReview
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationdiagnosiscompleted">
            DoctorConsultationDiagnosisCompleted
          </Link>
        </li>
        <li>
          <Link to="/doctorownpendingforreview">DoctorOwnPendingForReview</Link>
        </li>
        <li>
          <Link to="/doctorowndiagnosiscompleted">
            DoctorOwnDiagnosisCompleted
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationpendingforreviewbyradiologist">
            DoctorConsultationPendingForReviewByRadiologist
          </Link>
        </li>
        <li>
          <Link to="/doctorownpendingforreviewbyradiologist">
            DoctorOwnPendingForReviewByRadiologist
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationconsultotherdoctors">
            DoctorConsultationConsultOtherDoctors
          </Link>
        </li>
        <li>
          <Link to="/doctorownconsultotherdoctors">
            DoctorOwnConsultOtherDoctors
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationpendingforreviewbydoctorhistory">
            DoctorConsultationPendingForReviewByDoctorHistory
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationdiagnosiscompletedhistory">
            DoctorConsultationDiagnosisCompletedHistory
          </Link>
        </li>
        <li>
          <Link to="/doctorownpendingforreviewbydoctorhistory">
            DoctorOwnPendingForReviewByDoctorHistory
          </Link>
        </li>
        <li>
          <Link to="/doctorowndiagnosiscompletedhistory">
            DoctorOwnDiagnosisCompletedHistory
          </Link>
        </li>
        <li>
          <Link to="/doctorconsultationpendingforreviewbyradiologisthisto">
            DoctorConsultationPendingForReviewByRadiologistHisto
          </Link>
        </li>
        <li>
          <Link to="/doctorownpendingforreviewbyradiologisthistory">
            DoctorOwnPendingForReviewByRadiologistHistory
          </Link>
        </li>
        <li>
          <Link to="/superadminloginpage">SuperAdminLoginPage</Link>
        </li>
        <li>
          <Link to="/superadmindashboard">SuperAdminDashboard</Link>
        </li>
        <li>
          <Link to="/superadminreviewsignuprequests">
            SuperAdminReviewSignupRequests
          </Link>
        </li>
        <li>
          <Link to="/superadminviewadmins">SuperAdminViewAdmins</Link>
        </li>
        <li>
          <Link to="/superadminreviewaccountmodificationrequests">
            SuperAdminReviewAccountModificationRequests
          </Link>
        </li>
        <li>
          <Link to="/superadminreviewaccountdeletionrequests">
            SuperAdminReviewAccountDeletionRequests
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
